language: go

go:
  - "1.16"

services:
  - docker

cache:
  directories:
    - ${GOPATH}/pkg/mod

notifications:
  webhooks:
    if: type != pull_request
    urls:
      - https://coveralls.io/webhook?repo_token=COVERALLS_TOKEN

jobs:
  include:
    - name: "Unit test"
      if: type == pull_request
      script: make test
      env:
        - GO111MODULE=on

    - name: "Integration test"
      if: type == pull_request
      script: make run && sleep 15 && make test_integration
      env:
        - GO111MODULE=on

    - name: "Unit test (with coverage)"
      if: type != pull_request
      script: make test_cover upload_cover
      env:
        - GO111MODULE=on

    - name: "Integration test (with coverage)"
      if: type != pull_request
      script: make run && sleep 15 && make test_integration_cover upload_cover
      env:
        - GO111MODULE=on
