language: go

go:
  - "1.15"

services:
  - docker

cache:
  directories:
    - ${GOPATH}/pkg/mod

jobs:
  include:
    - name: "Test (unit)"
      if: type == pull_request
      script: make test
      env:
        - GO111MODULE=on

    - name: "Test (integration)"
      if: type == pull_request
      script: make run test_integration
      env:
        - GO111MODULE=on

    - name: "Test (unit with coverage)"
      stage: "Test"
      if: type != pull_request
      script: make test_cover
      env:
        - GO111MODULE=on

    - name: "Test (integration with coverage)"
      stage: "Test"
      if: type != pull_request
      script: make run test_integration_cover
      env:
        - GO111MODULE=on

    - name: "Publish coverage"
      stage: "Publish coverage"
      if: type != pull_request
      script: make test_cover publish_cover
      env:
        - GO111MODULE=on
