language: go

go:
  - "1.15"

services:
  - docker

cache:
  directories:
    - ${GOPATH}/pkg/mod

jobs:
  include:
    - name: "Unit test"
      if: type == pull_request
      script: make test
      env:
        - GO111MODULE=on

    - name: "Integration test"
      if: type == pull_request
      script: make run test_integration
      env:
        - GO111MODULE=on

    - name: "Unit test (with coverage)"
      stage: "Testing"
      if: type != pull_request
      script: make test_cover
      env:
        - GO111MODULE=on

    - name: "Integration test (with coverage)"
      stage: "Testing"
      if: type != pull_request
      script: make run test_integration_cover
      env:
        - GO111MODULE=on

    - name: "Coverage"
      stage: "Reporting"
      if: type != pull_request
      script: make publish_cover
      env:
        - GO111MODULE=on
