version: "3.4"

services:
  golang:
    image: golang:1.15
    environment:
      MONGO_HOST: "mongo:27017"
      PUBSUB_EMULATOR_HOST: "gpubsub:8793"
    volumes:
      - .:/eventhorizon
    working_dir: /eventhorizon

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"

  gpubsub:
    image: google/cloud-sdk:318.0.0
    ports:
      - "8793:8793"
    entrypoint:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - "--host-port=0.0.0.0:8793"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
