version: "3.4"

services:
  golang:
    image: golang:1.15
    environment:
      MONGO_HOST: "mongo:27017"
      PUBSUB_EMULATOR_HOST: "gpubsub:8793"
    volumes:
      - .:/eventhorizon
    working_dir: /eventhorizon

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  gpubsub:
    image: google/cloud-sdk:318.0.0
    ports:
      - "8793:8793"
    entrypoint:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - "--host-port=0.0.0.0:8793"

  zookeeper:
    image: bitnami/zookeeper:3.6.2
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
