name: golangci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1